# Generated by Django 5.1.7 on 2025-06-09 00:44

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(help_text="This is what's displayed on your profile!", max_length=50, validators=[django.core.validators.RegexValidator(message="Nicknames may contain letters, numbers, '.', '-' and '_' only.", regex='^[\\w.\\-]+$')], verbose_name='Display name'),
        ),
    ]
