# Generated by Django 5.1.7 on 2025-04-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('nationality', models.CharField(choices=[('GER', 'Germany'), ('GBR', 'United Kingdom'), ('USA', 'United States'), ('BRA', 'Brazil'), ('MDE', 'Middle Earth'), ('NAR', 'Narnia')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quotes.author')),
            ],
        ),
    ]
