# Generated by Django 5.1.7 on 2025-04-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='mood',
            field=models.CharField(choices=[('Love', 'Love'), ('Motivational', 'Motivational'), ('Analytical', 'Analytical'), ('Humble', 'Humble')], default='Love', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(choices=[('GER', 'Germany'), ('GBR', 'United Kingdom'), ('USA', 'United States'), ('BRA', 'Brazil'), ('MDE', 'Middle Earth'), ('NAR', 'Narnia')], max_length=50),
        ),
    ]
