# Generated by Django 5.1.7 on 2025-06-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name_plural': 'nationalities'},
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='quotes.nationality'),
        ),
        migrations.AddField(
            model_name='authorsubmission',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_submissions', to='quotes.nationality'),
        ),
    ]
