# Generated by Django 5.1.7 on 2025-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_mood_alter_author_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='mood',
            field=models.CharField(choices=[('Love', 'Love'), ('Motivational', 'Motivational'), ('Analytical', 'Analytical'), ('Humble', 'Humble'), ('Goofy', 'Goofy')], max_length=50),
        ),
    ]
