# Generated by Django 5.1.7 on 2025-06-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_nationality_options_author_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='code',
            field=models.CharField(default='US', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
