# Generated by Django 5.1.7 on 2025-05-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='mood',
            field=models.CharField(choices=[('love', 'Love'), ('motivational', 'Motivational'), ('analytical', 'Analytical'), ('humble', 'Humble'), ('goofy', 'Goofy')], max_length=50),
        ),
    ]
