# Generated by Django 5.1.7 on 2025-06-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_full_name_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotesubmission',
            old_name='pending_author',
            new_name='new_author_submission',
        ),
    ]
