# Generated by Django 5.1.7 on 2025-06-13 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_authorsubmission_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsubmission',
            name='author_obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.author'),
        ),
    ]
