# Generated by Django 5.1.7 on 2025-05-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quote_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
