# Generated by Django 5.1.7 on 2025-06-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_authorsubmission_author_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
    ]
