# Generated by Django 5.1.7 on 2025-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='mood',
            field=models.CharField(choices=[('love', 'Love'), ('motivational', 'Motivational'), ('analytical', 'Analytical'), ('humble', 'Humble'), ('silly', 'Silly')], max_length=50),
        ),
    ]
