# Generated by Django 5.1.7 on 2025-06-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_authorsubmission_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AlterField(
            model_name='quotesubmission',
            name='new_author_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quotes.authorsubmission'),
        ),
    ]
