# Generated by Django 5.1.7 on 2025-06-15 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_remove_quote_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
