# Generated by Django 5.1.7 on 2025-06-17 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quote_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
