# Generated by Django 5.1.7 on 2025-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20250621_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
