# Generated by Django 5.1.7 on 2025-06-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_alter_quote_bookmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='bookmarks',
            new_name='bookmarked_by',
        ),
    ]
