# Generated by Django 5.1.7 on 2025-06-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_alter_quote_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='moderation_comment',
            field=models.CharField(default='', help_text="Provide a justification regarding this quote's approval to the submitting user.", max_length=120),
            preserve_default=False,
        ),
    ]
