# Generated by Django 5.1.7 on 2025-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_alter_quotesubmission_moderation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesubmission',
            name='moderation_comment',
            field=models.CharField(blank=True, help_text="Provide a justification regarding this quote's approval decision to the submitting user.", max_length=120),
        ),
    ]
